config/routes.rb
Rails.application.routes.draw do

  root 'playlist#new' # Get genres
  
  post 'playlist' => 'playlist#create', as: :playlist_new , format: :false # Generate playlist
  post 'playlist/play' => 'playlist#show', as: :playlist_play, format: :false # Show player

end

app/models/genre.rb
#
# Class used to store the obtained genres from the provided scraped page
# 
# author: jdecastroc
# version: 2017/05/19/A
#
class Genre
    
    attr_accessor :name, :subgenres
    def initialize(name)
        @name = name
        @subgenres = []
    end
end

app/models/playlist.rb
#
# Class used as the main data structue which scrap and store the WebResources
# information. 
#
# @mode = Represents whether the different modes of the playlist. Random, from
# the newest...
#
# @deep = Represents how many pages the parse is going to go trough
#
# author: jdecastroc
# version: 2017/05/27/A
#

require 'nokogiri'
require 'open-uri'

class Playlist 
   
   attr_accessor :resources_list, :songs_list
   def initialize(name, resources_url, mode, deep)
      @name = name
      @mode = mode # Only random for now (1)
      @deep = deep
      @resources_list ||= []
      @songs_list ||= []
      
      resources_url.each { |url| 
         resource = WebResource.new("https://www.reddit.com/r/#{url}")
         get_resources(resource.name, deep, resource)
      }
      
      if (mode == 1) #Get songs list and randomize
         @resources_list.each { |resource|

            resource.songs.each { |song|
               @songs_list.push(song)
            }
            
         }
         @songs_list.shuffle!
      end
      
   end
   
   def get_resources(url, deep, resource)
      puts "Im in url: #{url}" #debug option
      
	   doc = Nokogiri::HTML(open(url, 
	         'User-Agent' => 'web:com.ReddMusic.surfReddit:v1.4 ALPHA by /u/hoppy93'))

      doc.css("div[data-domain='youtube.com']").css("a.title").map{ |node| 
   
      name = node.content
      url = node['data-href-url'][/(?<=[?&]v=)[^&$]+/]

      resource.songs.push(Song.new(url, name))
      #puts "Im in name: #{name}" #debug purpose
      }
      
      next_page = doc.at_css("span.next-button").css('a').attr('href')
      deep = deep - 1
        
      if deep.zero?
         return @resources_list.push(resource)
      end
        
      get_resources(next_page, deep, resource)
 
   end
   
end

app/models/song.rb
#
# Class used to store the songs info which belongs to WebResource.songs array
# 
# author: jdecastroc
# version: 2017/05/19/A
#
class Song
   
   attr_accessor :url, :name
   def initialize(url, name) 
       @url = url
       @name = name
   end
   
end

app/models/subgenre.rb
#
# Class used to store the subgenres of the scrapped genres
# 
# author: jdecastroc
# version: 2017/05/19/A
#
class Subgenre
    
    attr_accessor :name, :url
    def initialize(name, url)
        @name = name
        @url = url
    end
end

app/models/web_resource.rb
#
# Each web resource data structure belongs to a scrapped resource. It store 
# the obtained data
# 
# author: jdecastroc
# version: 2017/05/19/A
#
class WebResource
    
   attr_accessor :name, :songs
   def initialize(name)
        @name = name
        @songs = []
   end
   
   #def to_hash
   #    songs = Hash[@songs.collect { |song| [song.url, song.name] } ]
   #    songs.to_json
   #    playlist = {:name => name, :songs => songs}
   #end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_controller.rb
#
# Main controller class for the project
# 
# author: jdecastroc
# version: 2017/05/27/A
# see <a href = "https://github.com/jdecastroc/music-discoverer" /> Github
#      repository </a>
# TODO:
# => ADD STATE TO THE REQUEST (SUCCES, FAIL AND CODES)
# => ADD LOGGER FOR ROR
# => CHECK THE FLASH NOTICES
# => ADD TRY/CATCH BLOCKS IN THE PARSING WITH NOKOGIRI
#

require 'nokogiri'
require 'open-uri'

# Main controller class which get the genres from the GENRES_URL page
# web resource and create a playlist given x number of web resources looking
# for youtube links. (Check class diagram for more info)
class PlaylistController < ApplicationController
    
    GENRES_URL = "https://www.reddit.com/r/Music/wiki/musicsubreddits"
    GENRES_EXCEPTIONS = []
    
    # Get the genres links from GENRES_URL and render them into the new.html.erb
    # page as a form
    #
    def new
        
        @genres = []
        get_genres()

    end
    
    # Get the parameters from the playlist form and call the scrapper to build
    # the playlist and load it
    #
    def create
        
        @playlist = Playlist.new("",params[:items],1,2) #name, resources, mode (only random for now), deep
       
    end

    private
    
    # Get the genres from GENRES_URL in order to build the form
    #
    def get_genres

	    doc = Nokogiri::HTML(open(GENRES_URL, 
	   'User-Agent' => 'web:com.ReddMusic.surfReddit:v1.4 ALPHA by /u/hoppy93'))
	    
	    doc.css("div.md").css('h2, a').each { |node|
	    
	        current_genre ||= "" # Current object where storing data
	        parsing_genre ||= "" # New parsed tag
	        genres_counter = -1 # Used for store subgenres in the array
	        
	        if node.name == 'h2'
	            parsing_genre = node.attr('id')
	            
	            if parsing_genre != current_genre
	                current_genre = parsing_genre
	                #puts node.attr('id') # debug purpose
	                @genres.push(Genre.new(node.attr('id')))
	                genres_counter += 1
	            end
	            
	        end
	        
	        if node.name == 'a' && !@genres[genres_counter].nil?
	            if parsing_genre == current_genre
	                #puts "It is #{node.attr('href')}" # debug purpose
	                @genres[genres_counter]
	                .subgenres
	                .push(Subgenre.new(node.text.strip,node.attr('href')))
	            end
	            
	        end
	        
        }
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="panel panel-default">
    <div class="panel-footer" style="height: 70;">
      <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <div class="col-md-4">

            </div>
            <div class="col-md-4 text-center">
              <p style="font-size:80%;">Music discoverer is a web crawler application made for enjoy the music</p>
              <p style="font-size:80%;">Copyright (C) 2017 <a href="https://github.com/jdecastroc">@jdecastroc</p></a>
            </div>
            <div class="col-md-4 text-center">
            
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <ul class="nav navbar-nav dropdown-toggle">
            <li class="dropdown">
                <!---Login container starts-->
                <a href="#" class="dropdown-toggle glyphicon glyphicon-user" data-toggle="dropdown"></a>
                <ul class="dropdown-menu dropdown-lr animated slideInLeft" role="menu">
                <div class="col-lg-12">
                    <div class="text-center"><h3><b>Log In</b></h3></div>
                    <form id="ajax-login-form" action="#" method="post" role="form" autocomplete="off">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-xs-7">
                                    <input type="checkbox" tabindex="3" name="remember" id="remember">
                                    <label for="remember">Remember Me</label>
                                </div>
                                <div class="col-xs-5 pull-right">
                                    <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-info" value="Log In">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="text-center">
                                        <a href="#" tabindex="5" class="forgot-password">Forgot Password?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                </ul>
            </li>
            <!---Login container ends-->
            <li><a href="#"><i class="glyphicon glyphicon-heart"></i></a></li>
            <li><a href="#"><i class="glyphicon glyphicon-star"></i></a></li>
        </ul>

        <!--language selection bar-->
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">JP</a></li>
            <li><a href="#">EN</a></li>
            <li><a href="#">SP</a></li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<html lang="en">
<head>

  <title>Reddit Music Player</title>
  <meta name="title" content="Reddit Music Player">
  <meta name="description" content="Make playlists of your favorite music from Reddit.">
  <meta name="keyword" content="reddit, music player, redditor, reddit music, music, mind state music">

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/navigation' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/playlist/create.html.erb
<div class="row">
  <div class="col-md-8" id="player_container">
    <div class="well">
      <div class="text-center">
        <h2><%= params[:items].each { |item| puts "#{item}, "} %></h2><hr class="hr-tags"/>
        <div class="player-wrapper" style="margin-top: 20px;">
        </div>
        <button id="previous" type="button" class="btn btn-primary" style="position:relative; margin-top: 20px;"><span class="glyphicon glyphicon-backward" aria-hidden="true"></span>Previous video</button>
        <button id="next" type="button" class="btn btn-primary" style="position:relative; margin-top: 20px;"><span class="glyphicon glyphicon-forward" aria-hidden="true"></span>Next video</button>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="well">
      <h2>Playlist</h2><hr class="hr-tags"/>
      <ul class="media-list main-list" id="links_container">
      <% @playlist.songs_list.each { |song| %>
        <li class="media">
				  <a class="pull-left" href="#">
					  <img class="media-object" src="http://img.youtube.com/vi/<%= song.url %>/default.jpg" alt="...">
					</a>
					<div class="media-body">
					  <h4 class="media-heading"><a href="#" onclick = "playThisVideo('<?php echo $data[$counter]?>')"><%= song.name %></a></h4>
					</div>
				</li>
      <% } %>
      </ul>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).on('ready page:load', function () {
  
  // Initialization of the song list iterator and the json list with the songs
  var song_counter = 0
  var song_list = <%= @playlist.songs_list.to_json.html_safe %>;
  
  // Addition of the event listeners for the player buttons
  document.getElementById('previous').addEventListener('click', previousVideo, true);
  document.getElementById('next').addEventListener('click', nextVideo, true);
  
  document.getElementById("previous").style.display = "none";

  
  // 2. This code loads the IFrame Player API code asynchronously.
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
      
  player_wrapper = $('.player-wrapper');
  player_wrapper.append('<div id="ytPlayer"><p>Loading player...</p></div>');
  // 3. This function creates an <iframe> (and YouTube player)
  //    after the API code downloads.
  var player;
      
  //onYouTubeIframeAPIReady();
  window.onYouTubeIframeAPIReady = function() {
  player = new YT.Player('ytPlayer', {
          height: '360',
          width: '640',
          videoId: song_list[song_counter].url,
          events: {
            'onReady': onPlayerReady,
						'onStateChange': onPlayerStateChange,
						'onError': onPlayerError
          }
        });
  }

  // 4. The API will call this function when the video player is ready.
  function onPlayerReady(event) {
    showPlayerOptions();
    event.target.playVideo();
  }

  // 5. The API calls this function when the player's state changes.
  //    The function indicates that when playing a video (state=1),
  //    the player should play for six seconds and then stop.
  var done = false;
  function onPlayerStateChange(event) {
    if (event.data == 0) { //CUANDO TERMINA PASA AL SIGUIENTE EN EL ARRAY
			song_counter++;
			showPlayerOptions();
			player.loadVideoById(song_list[song_counter].url);
		}
  }
  
  function stopVideo() {
    player.stopVideo();
  }
      
  function onPlayerError(event) {
		song_counter++;
		showPlayerOptions();
		player.loadVideoById(song_list[song_counter].url);
	}
      
  function nextVideo() {
	  song_counter++;
		showPlayerOptions();
		player.loadVideoById(song_list[song_counter].url);
	}
			
	function previousVideo() {
		song_counter--;
		showPlayerOptions();
		player.loadVideoById(song_list[song_counter].url);
	}

	function showPlayerOptions() {
		if (song_counter <= 0) {
		  document.getElementById("previous").style.display = "none";
		} 
		    
		if (song_counter > 0) {
      document.getElementById("previous").style.display = "inline";
    }
        
		if (song_counter < song_list.length) {
      document.getElementById("next").style.display = "inline";
    }
        
    if (song_counter >= song_list.length) {
      document.getElementById("next").style.display = "none";
    }
  }
});
</script>

app/views/playlist/new.html.erb
<h1>Make your own Playlist!</h1>

<%= form_tag(playlist_new_path, method: "post") do %>
    <% @genres.each { |genre| %>
        <h2><%= genre.name %></h2>
        <ul>
        <% genre.subgenres.each { |subgenre| %>
            <%= check_box_tag "items[]", "#{subgenre.name[3..-1]}", false, 
            {:class => "check_class"} -%>
            <%= label_tag(subgenre.name[3..-1].downcase) -%>
            <br>
        <% } %>
        </ul>
    <% } %>
    <%= submit_tag("send") %>
<% end %>

<script type="text/javascript">
$(document).on('ready page:load', function () {
;
    var checkboxes = document.querySelectorAll('input[type=checkbox]');
    
    // add a change event listener for each checkbox
    for(var i = 0; i < checkboxes.length; i++) {
        checkboxes[i].addEventListener('change', function(){
            checkInput();
        });
    }
    
    //Block the checkboxes after 4
    function checkInput(){
        var numberOfChecked = $('input[name="items[]"]:checked').length;
        
    	if (numberOfChecked >= 4) {
    	    $('input[type=checkbox]:not(:checked)').attr('disabled', 'disabled');
        } else {
            $('input[type=checkbox]').removeAttr("disabled")
        }
    }
});
</script>